doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: 'mariadb-10.4.12'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Domain:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/config/mapping/orm/domain'
        prefix: 'App\Domain'
        alias: Domain
      Projections:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/config/mapping/orm/projections'
        prefix: 'App\Infrastructure'
        alias: Projections