security:
  encoders:
    App\Entity\Account:
      algorithm: auto
  providers:
    users:
      id: 'App\Infrastructure\User\Auth\AuthProvider'
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api_refresh:
      pattern:  ^/api/login/refresh
      stateless: true
      anonymous: true
    api_doc:
      pattern:  ^/api/doc
      stateless: true
      anonymous: true
    api_login:
      pattern:  ^/api/login
      stateless: true
      anonymous: true
      json_login:
        check_path:      /api/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    api:
      pattern:   ^/api
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
    sso:
      pattern: ^/sso
      stateless: false
      anonymous: true
      lazy: true
      logout:
        path: sso_logout
      guard:
        authenticators:
          - App\Security\SSOAuth
    gui:
      stateless: false
      anonymous: true
      lazy: true
      provider: users
      guard:
        entry_point: 'App\Infrastructure\User\Auth\Guard\LoginFormAuthenticator'
        authenticators:
          - 'App\Infrastructure\User\Auth\Guard\LoginFormAuthenticator'
      logout:
        path: logout
      remember_me:
        secret:   '%kernel.secret%'
        lifetime: 604800 # 1 week in seconds
        path:     /

  access_control:
    - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/login/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY  }
