gesdinet_jwt_refresh_token:
  path:       /api/auth/refresh
  methods:     [POST]
  controller: gesdinet.jwtrefreshtoken::refresh

api_controllers:
  resource: '../src/UI/Http/Rest/Controller/'
  type: annotation
  prefix: /api

web_controllers:
  resource: '../src/UI/Http/Web/Controller/'
  type: annotation