parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migration,Tests,Kernel.php}'
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
  App\EventListener\HashableListener:
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }
  App\EventListener\UniquableListener:
    tags:
      - { name: doctrine.event_listener, event: prePersist }